company:
    resource: "@CompanyBundle/Resources/config/routing.yml"
    prefix:   /rest

contact:
    resource: "@PersonBundle/Resources/config/routing.yml"
    prefix:   /rest

app:
    resource: @AppBundle/Controller/
    type:     annotation