services:
#    nemo64_entity_extra.example:
#        class: Nemo64\EntityExtraBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    entity_extra.property_listener:
        abstract: true
        class: Nemo64\EntityExtraBundle\Listener\AbstractPropertyListener
        calls:
            - [setStopwatch, [@templating.helper.stopwatch]]

    nemo64_entity_extra.create_time_listener:
        private: true
        class: Nemo64\EntityExtraBundle\Listener\EntityCreateTimeListener
        # calls will be added dynamically
        tags:
            - { name: entity_extra.property_listener, annotation: Nemo64\EntityExtraBundle\Annotation\CreateTime }
            - { name: doctrine.event_listener, event: onFlush }

    nemo64_entity_extra.create_ip_listener:
        private: true
        class: Nemo64\EntityExtraBundle\Listener\EntityCreateIpListener
        arguments: [@request_stack]
        # calls will be added dynamically
        tags:
            - { name: entity_extra.property_listener, annotation: Nemo64\EntityExtraBundle\Annotation\CreateIp }
            - { name: doctrine.event_listener, event: onFlush }